# Practicando NumPy: demos guiadas y ejercicios resueltos

In [56]:
import numpy as np

Sección 1: Construcción de un arreglo unidimensional (vector) con NumPy.
Comentario: Un arreglo 1D tiene forma (3,) indicando 3 elementos en una dimensión. Podemos (de forma directa) acceder a elementos por índice [0] o usar segmentación (slicing) [0:2] para obtener subarrays.

In [57]:
print("="*80)
print("DEMO 1: Arrays 1D - Vector Simple")
print("="*80)
x = np.array([1, 2, 3])
print("Array:", x)
print("Shape:", x.shape)  # tupla de dimensiones  # (3,) indica 3 elementos en una dimensión
print("Primer elemento:", x[0])  # Acceso por índice
print("Slice [0:2]:", x[0:2])  # Slicing: obtiene elementos del índice 0 al 1
print()

EJEMPLO 1: Arrays 1D - Vector Simple
Array: [1 2 3]
Shape: (3,)
Primer elemento: 1
Slice [0:2]: [1 2]



Sección 2: Arreglos 2D - Matriz (2D)
Construcción de un arreglo bidimensional (matriz). Un arreglo 2D tiene forma (2, 3) = 2 filas y 3 columnas. Es como una tabla o matriz matemática.

In [58]:
print("="*80)
print("DEMO 2: Arrays 2D - Matriz")
print("="*80)
x = np.array([[5, 4, 2], [-1, 0, 3]])
print("Array:\n", x)
print("Shape:", x.shape)  # tupla de dimensiones  # (2, 3) = 2 filas y 3 columnas

EJEMPLO 2: Arrays 2D - Matriz
Array:
 [[ 5  4  2]
 [-1  0  3]]
Shape: (2, 3)


Sección 3: Arreglos 3D - Tensor multidimensional
 Arreglo tridimensional, útil para imágenes o datos volumétricos
 Dimensión (3, 2, 3) significa: 3 matrices, cada una de 2 filas y 3 columnas. Piensa en ello como 3 'capas' de matrices 2x3.

In [59]:
# Crear un tensor 3D
x = np.array([[[5, 4, 2], [-1, 0, 3]], 
              [[5, 4, 2], [-1, 0, 3]], 
              [[5, 4, 2], [-1, 0, 3]]])
print("Shape:", x.shape)  # tupla de dimensiones  # (3, 2, 3) = 3 matrices de 2x3
print("Tensor:\n", x)

Shape: (3, 2, 3)
Tensor:
 [[[ 5  4  2]
  [-1  0  3]]

 [[ 5  4  2]
  [-1  0  3]]

 [[ 5  4  2]
  [-1  0  3]]]


Sección 4: Arreglos 4D - Hiperdimensional
Arreglos de mayor dimensión, comunes en deep learning. Dimensión (5, 3, 2, 3) = 5 grupos de tensores 3D. El segmentación (slicing) y[0:2] extrae los primeros 2 grupos, resultando en shape (2, 3, 2, 3).

In [60]:
# Crear tensor 3D base
x = np.array([[[5, 4, 2], [-1, 0, 3]], 
              [[5, 4, 2], [-1, 0, 3]], 
              [[5, 4, 2], [-1, 0, 3]]])

# Crear tensor 4D apilando el tensor 3D
y = np.array([x, x, x, x, x])
print("Shape de y:", y.shape)  # tupla de dimensiones  # (5, 3, 2, 3) = 5 grupos de tensores 3D
print("Shape de y[0:2]:", y[0:2].shape)  # tupla de dimensiones  # Slicing en la primera dimensión

Shape de y: (5, 3, 2, 3)
Shape de y[0:2]: (2, 3, 2, 3)


Sección 5: Operaciones Matriciales
Multiplicación de matrices y matriz inversa. El operador @ hace multiplicación matricial. x.transpose() intercambia filas y columnas. La inversa multiplicada por la matriz original da la matriz identidad (1s en diagonal, 0s fuera).

In [61]:
# Definir matriz
x = np.array([[5, 4, 2], [-1, 0, 3]])
print("Matriz x:")
print(x)

# Multiplicación matricial: x @ x^T
y = x @ x.transpose()
print("\nx @ x.T =")
print(y)

# Verificar que Inversa * Matriz = Identidad
print("\nInversa de y multiplicada por y (debe dar identidad):")
resultado = np.linalg.inv(y) @ y
print(resultado)

Matriz x:
[[ 5  4  2]
 [-1  0  3]]

x @ x.T =
[[45  1]
 [ 1 10]]

Inversa de y multiplicada por y (debe dar identidad):
[[1. 0.]
 [0. 1.]]


Sección 6: Funciones en Python
 Las funciones pueden recibir parámetros y retornar valores. Aquí hello() imprime un mensaje y retorna 10, independientemente del parámetro recibido.

In [62]:
def hello(a):
    print("Hello, world!")
    return 10

# Llamar a la función
b = hello([3, 4])
print("Valor retornado:", b)

Hello, world!
Valor retornado: 10


Sección 7: Programación Orientada a Objetos - Clase Base
Construcción de una clase y sus instancias.El método __init__ es el constructor. Cada instancia (x, y) tiene su propio atributo 'nombre'. El método sonido() está vacío (pass) y será implementado por las subclases

In [63]:
class Animal:
    def __init__(self, nombre):
        self.nombre = nombre
    
    def sonido(self):
        pass  # Método vacío, será implementado por subclases

# Crear instancias
x = Animal("Perro")
y = Animal("Gato")

print("Animal x:", x.nombre)
print("Animal y:", y.nombre)

Animal x: Perro
Animal y: Gato


Sección 8: Herencia - Subclases
Clases que heredan de Animal e implementan sonido(). Las subclases Gato y Perro heredan de Animal pero implementan su propio método sonido(), objetos diferentes responden al mismo método de forma distinta.

In [64]:
class Animal:
    def __init__(self, nombre):
        self.nombre = nombre
    
    def sonido(self):
        pass

class Gato(Animal):
    def sonido(self):
        return "Miau"

class Perro(Animal):
    def sonido(self):
        return "Guau"

# Crear instancias de las subclases
a = Gato("Pelusa")
b = Perro("Patricio")

print(a.nombre, "hace", a.sonido())
print(b.nombre, "hace", b.sonido())

Pelusa hace Miau
Patricio hace Guau


## EJERCICIOS PRÁCTICOS
EJERCICIO 1: Operaciones con Arreglos
Problema: Crea dos arreglos 1D de tamaño 5 con valores aleatorios y calcula: suma, resta, producto elemento a elemento y producto punto. NumPy permite operaciones vectorizadas. +, -, * operan elemento a elemento. np.dot() calcula el producto punto (suma de productos).

In [65]:
# Crear dos arrays aleatorios
a = np.random.rand(5)
b = np.random.rand(5)

print("Array a:", a)
print("Array b:", b)
print("\nSuma:", a + b)
print("Resta:", a - b)
print("Producto elemento a elemento:", a * b)
print("Producto punto:", np.dot(a, b))

Array a: [0.35749533 0.77083059 0.47971366 0.01891184 0.8046525 ]
Array b: [0.26756687 0.27390345 0.74206996 0.83614743 0.95110167]

Suma: [0.62506219 1.04473404 1.22178362 0.85505927 1.75575417]
Resta: [ 0.08992846  0.49692713 -0.2623563  -0.81723559 -0.14644917]
Producto elemento a elemento: [0.0956539  0.21113316 0.35598109 0.01581308 0.76530633]
Producto punto: 1.4438875768997996


EJERCICIO 2: Indexación y Slicing
Problema: Dada una matriz 4x4, extrae la submatriz del centro 2x2.
El segmentación (slicing) [1:3, 1:3] extrae filas de índice 1 a 2 y columnas de índice 1 a 2 (el índice final no se incluye).

In [66]:
# Crear matriz 4x4 con valores de 0 a 15
matriz = np.arange(16).reshape(4, 4)
print("Matriz original:")
print(matriz)

# Extraer la submatriz del centro 2x2
centro = matriz[1:3, 1:3]  # Filas 1-2, Columnas 1-2
print("\nCentro 2x2:")
print(centro)

Matriz original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Centro 2x2:
[[ 5  6]
 [ 9 10]]


EJERCICIO 3: Broadcasting
Problema: Suma un escalar a cada elemento de una matriz y multiplica cada fila por un vector diferente. Broadcasting permite operaciones entre arreglos de diferentes shapes. NumPy automáticamente 'expande' el escalar o vector para que coincida con la matriz.

In [67]:
# Crear matriz 3x4
matriz = np.arange(12).reshape(3, 4)
print("Matriz original:")
print(matriz)

# Sumar escalar (broadcasting automático)
print("\nMatriz + 10:")
print(matriz + 10)

# Multiplicar cada fila por un vector
vector = np.array([1, 2, 3, 4])
print("\nMatriz * vector [1, 2, 3, 4]:")
print(matriz * vector)

Matriz original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Matriz + 10:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Matriz * vector [1, 2, 3, 4]:
[[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]]


EJERCICIO 4: Funciones de Agregación
Problema: Calcula la media, desviación estándar, mínimo y máximo de un arreglo, tanto globalmente como por eje, axis=0 opera sobre columnas (colapsa filas), axis=1 opera sobre filas (colapsa columnas). Sin axis opera sobre todo el arreglo.

In [68]:
# Crear matriz 3x4 con valores aleatorios entre 0 y 100
matriz = np.random.randint(0, 100, (3, 4))
print("Matriz:")
print(matriz)

print("\nEstadísticas globales:")
print("Media:", np.mean(matriz))
print("Desviación Estándar:", np.std(matriz))
print("Mínimo:", np.min(matriz))
print("Máximo:", np.max(matriz))

print("\nMedia por columnas (axis=0):")
print(np.mean(matriz, axis=0))

print("\nMedia por filas (axis=1):")
print(np.mean(matriz, axis=1))

Matriz:
[[98 55 15 45]
 [15 98 71 26]
 [ 7 94 74 98]]

Estadísticas globales:
Media: 58.0
Desviación Estándar: 34.18332927027442
Mínimo: 7
Máximo: 98

Media por columnas (axis=0):
[40.         82.33333333 53.33333333 56.33333333]

Media por filas (axis=1):
[53.25 52.5  68.25]


EJERCICIO 5: Reshape y Flatten
Problema: Transforma un arreglo de diferentes formas usando reshape y flatten, reshape() cambia las dimensiones del arreglo sin modificar los datos. flatten() convierte cualquier arreglo a 1D.

In [69]:
# Crear array 1D con 24 elementos
arr = np.arange(24)
print("Array original:", arr)
print("Shape:", arr.shape)  # tupla de dimensiones

# Reshape a 3 dimensiones
reshaped = arr.reshape(2, 3, 4)
print("\nReshape a (2, 3, 4):")
print(reshaped)

# Flatten: volver a 1D
flattened = reshaped.flatten()
print("\nFlatten (volver a 1D):")
print(flattened)

Array original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Shape: (24,)

Reshape a (2, 3, 4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Flatten (volver a 1D):
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


EJERCICIO 6: Máscaras Booleanas
Problema: Filtra elementos de un arreglo usando condiciones booleanas, las cuales permiten filtrar y modificar elementos que cumplen ciertas condiciones. Es una técnica muy poderosa para procesamiento de datos.

In [70]:
# Crear array
arr = np.array([1, 5, 10, 15, 20, 25])
print("Array original:", arr)

# Crear máscara booleana
mascara = arr > 10
print("Máscara (arr > 10):", mascara)
print("Elementos mayores a 10:", arr[mascara])

# Modificar elementos que cumplen condición
arr[arr > 10] = 999
print("Array modificado (valores > 10 se vuelven 999):", arr)

Array original: [ 1  5 10 15 20 25]
Máscara (arr > 10): [False False False  True  True  True]
Elementos mayores a 10: [15 20 25]
Array modificado (valores > 10 se vuelven 999): [  1   5  10 999 999 999]


EJERCICIO 7: Concatenación y Apilamiento
Problema: Combina matrices usando diferentes métodos de concatenación, vstack() apila verticalmente (añade filas), hstack() apila horizontalmente (añade columnas).

In [71]:
# Crear dos matrices
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matriz a:")
print(a)
print("\nMatriz b:")
print(b)

# Concatenar verticalmente
print("\nConcatenar verticalmente (vstack):")
print(np.vstack([a, b]))

# Concatenar horizontalmente
print("\nConcatenar horizontalmente (hstack):")
print(np.hstack([a, b]))

Matriz a:
[[1 2]
 [3 4]]

Matriz b:
[[5 6]
 [7 8]]

Concatenar verticalmente (vstack):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenar horizontalmente (hstack):
[[1 2 5 6]
 [3 4 7 8]]


EJERCICIO 8: Álgebra Lineal Avanzada
Problema: Calcula el determinante, traza, valores propios y vectores propios de una matriz. NumPy incluye funciones de álgebra lineal en np.linalg. Los valores propios y vectores propios son fundamentales en muchos algoritmos de machine learning.

In [72]:
# Crear matriz cuadrada
matriz = np.array([[4, 2], [1, 3]])
print("Matriz:")
print(matriz)

# Calcular determinante
print("\nDeterminante:", np.linalg.det(matriz))

# Calcular traza (suma de la diagonal)
print("Traza (suma de diagonal):", np.trace(matriz))

# Calcular valores y vectores propios
valores, vectores = np.linalg.eig(matriz)
print("\nValores propios:", valores)
print("Vectores propios:")
print(vectores)

Matriz:
[[4 2]
 [1 3]]

Determinante: 10.000000000000002
Traza (suma de diagonal): 7

Valores propios: [5. 2.]
Vectores propios:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
