# Aprendiendo y practicando NumPy con ejemplos y ejercicios

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])

In [4]:
x.shape

(3,)

In [5]:
x[0]

1

In [13]:
x[0:2]

array([1, 2])

In [15]:
x = np.array([[5, 4, 2], [-1, 0, 3 ]])

In [16]:
x

array([[ 5,  4,  2],
       [-1,  0,  3]])

In [17]:
x.shape

(2, 3)

In [20]:
x = np.array([[[5, 4, 2], [-1, 0, 3 ]], [[5, 4, 2], [-1, 0, 3 ]], [[5, 4, 2], [-1, 0, 3 ]]])

In [23]:
x.shape

(3, 2, 3)

In [24]:
y = np.array([x, x, x, x, x])

In [25]:
y.shape

(5, 3, 2, 3)

In [28]:
y[0:2].shape

(2, 3, 2, 3)

In [29]:
x = np.array([[5, 4, 2], [-1, 0, 3 ]])

In [30]:
x

array([[ 5,  4,  2],
       [-1,  0,  3]])

In [33]:
y = x @ x.transpose()

In [34]:
y

array([[45,  1],
       [ 1, 10]])

In [36]:
np.linalg.inv(y) @ y

array([[1.00000000e+00, 8.67361738e-19],
       [0.00000000e+00, 1.00000000e+00]])

In [47]:
def hello(a):
    print("Hello, world!")
    return 10

In [51]:
b = hello([3,4])

Hello, world!


In [52]:
b

10

In [62]:
class Animal:
    def __init__(self, nombre):
        self.nombre = nombre

    def sonido(self):
        pass

In [63]:
x = Animal("Perro")

In [64]:
x.nombre

'Perro'

In [65]:
y = Animal("Gato")

In [66]:
y.nombre

'Gato'

In [71]:
class gato(Animal):
    def sonido(self):
        return "Miau"

class perro(Animal):
    def sonido(self):
        return "Guau"

In [68]:
a = gato("Pelusa")

In [69]:
a.nombre

'Pelusa'

In [70]:
a.sonido()

'Miau'

In [72]:
b = perro("Patricio")

In [76]:
print(a.nombre, "hace", a.sonido())
print(b.nombre, "hace", b.sonido())


Pelusa hace Miau
Patricio hace Guau
